# -*- coding: utf-8 -*-
"""Data Structure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sxxtkp4b34TR9YtHY3-9YpTGwYczme_j
"""

#STATEMENT AND VARIABEL
#variable = tempat menyimpan data sementara
a = 5 #otomatis menjadi bilangan bulat (integer)
b = 6.0 #bilangan real
c = "nilai saya " #string
d = a + b
print(c + str(d))

#SELEKSI KONDISI
#memilih suatu kondisi yang terpenuhi
#fungsi aktivasi ==> ReLU... if(n > 0) maka n, else if (n < 0) maka 0
n = int(input("Masukkan Nilai: ")) #menerima input dari keyboard, kemudian casting ke int
if (n > 0):
  print("nilai: "+str (n))
else:
  print("nilai: "+str (0))

#input n = 0 - 100
# A: 85 - 100
# B: 70 - 84
# C: 60 - 69
# D: <60
#LAZY CONDITION: AND, OR 

n = int (input("Masukkan Nilai: "))
if (n>=85 and n<=100): #AND:== 1 & 1 = 1, 1 & 0 = 0, 0 & 1 = 0, 0 & 0 = 0
  print("A")
elif (n>=70 and n<=84):
  print("B")
elif (n>=60 and n<=69):
  print("C")
elif (n<=59 and n>=0):
  print("D")
else:
  print("Salah")

#PERULANGAN
n = int(input("nil: "))
i = 0 #wariable bantu i, inisialisasi = 0
while (i < n): #perintah perulangan while (cek kondisi apakah terpenuhi)
  print("Nil-" +str(i))
  i = i + 1
print("Selesai")